Table documents {
  id uuid [primary key]
  source text //NDMA, NEOC, etc.
  posted_date date
  title text
  url text
  filename text
  filetype text
  processed_at datetime [default: null]
}

Table places {
  id uuid [primary key]
  name text [not null]
  parent uuid [ref: > places.id, null]
  hierarchy_level int //province, disctrict, etc.
  polygon geometry(Polygon, 4326) [not null]
}

Table alerts {
  id uuid [primary key]
  document_id uuid [ref: > documents.id]

  //Core CAP fields
  category alert_category
  event text
  urgency alert_urgency
  severity alert_severity
  description text
  instruction text

  // Overall alert timeframe (can be overridden per location)
  effective_from timestamp [not null]
  effective_until timestamp [not null]
}

Table alert_areas {
  id uuid [primary key]
  alert_id uuid [not null, ref: > alerts.id]
  place_id uuid [not null, ref: > places.id]

  // Location-specific values (optional overrides)
  specific_effective_from timestamp [default: null]
  specific_effective_until timestamp [default: null]
  specific_urgency alert_urgency [default: null]
  specific_severity alert_severity [default: null]
  specific_instruction text [default: null]

  indexes {
    (alert_id, place_id)
  }
}
  
Enum alert_category {
  Geo
  Met
  Safety
  Security
  Rescue	
  Fire	
  Health	
  Env
  Transport	
  Infra	
  CBRNE	
  Other
}

Enum alert_urgency {
  Immediate 
  Expected
  Future
  Past
  Unknown
}

Enum alert_severity {
  Extreme
  Severe
  Moderate
  Minor
  Unknown
}